global:
  scrape_interval: 15s

scrape_configs:

  - job_name: 'uploader'
    static_configs:
      - targets: ['uploader:8002']

  - job_name: 'worker'
    static_configs:
      - targets: ['worker:8003']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq-exporter:9419']
