global:
  scrape_interval: 15s # 每 15 秒收集一次数据

scrape_configs:
  # 1. 监控 Uploader 服务 (我们将会在代码里开启 8002 端口)
  - job_name: 'uploader'
    static_configs:
      - targets: ['uploader:8002']

  # 2. 监控 Worker 服务 (我们将会在代码里开启 8003 端口)
  - job_name: 'worker'
    static_configs:
      - targets: ['worker:8003']

  # 3. 监控 RabbitMQ (通过 Exporter)
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq-exporter:9419']
